### ISSUE TITLE
Kind of roadmap

### ISSUE THREAD

**Issue by MasterEnderman** [Ender-Development/Soot-Extended-Life#2]
- [x] fix links in README.md
- [x] depend on a more recent version of our Embers fork to implement the mod instance in various places instead of hardcoding everything twice
- [ ] move the nugget stamp stuff into the main mod
- [x] check compat with Embers' Construct
- [ ] check compat with Planar Artifice: Continuation
